### PR TITLE
Adds responseStatus to o365 event, required by staff api

### PR DESCRIPTION
**Pull request by websymphony**
https://docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0

### CODE REVIEW

**Comment by websymphony** [comment]
I think it makes more sense to have this for attendee, rather than event. There isn't equivalent of https://developers.google.com/calendar/v3/reference/events/ `status` for o365. 

Maybe we can use `isCancelled` from https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0 to set `status` as `cancelled` and nil otherwise.

Will update!

**Comment by stakach** [comment]
The reason it exists for the event is to see if the resource calendar has accepted the event
As sometimes meeting rooms are reserved for special use and use needs to be approved by someone

**Comment by stakach** [comment]
They look pretty similar

Google
    "needsAction" - The attendee has not responded to the invitation.
    "declined" - The attendee has declined the invitation.
    "tentative" - The attendee has tentatively accepted the invitation.
    "accepted" - The attendee has accepted the invitation.

Office - breakdown here: https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascal/00069422-927f-41ad-b068-90007a1b0d45
  None (`needsAction`)
  Organizer (`accepted`)
  TentativelyAccepted (`tentative`)
  Accepted (`accepted`)
  Declined (`declined`)
  NotResponded (`needsAction`)

**Comment by websymphony** [comment]
I was trying to standardise the status field here for the event: https://github.com/place-labs/google-staff-api/blob/master/src/controllers/application.cr#L133

So the google event has a `status` field with possible statuses as "confirmed", "tentative", "cancelled" and o365 event has `responseStatus` field with possible responses as `None, Organizer, TentativelyAccepted, Accepted, Declined, NotResponded`.

My assumption was that these google event status/ o365 event responseStatus fields are equivalent where:
Google event statuses: "confirmed", "tentative", "cancelled"
Corresponding o365 event response statuses: "Accepted", "TentativelyAccepted", "Declined"  

Does the above seem accurate?

Also both google and o365 attendees have `responseStatus` fields which is what you have mentioned above. 

We don't have that for o365 Attendee's yet. Will add it as part of this PR.

**Pull request merged**
